import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '../widgets/Header';
import {
  ISearchQueryContext,
  SearchQueryContext,
  SearchQueryProvider,
} from '../contexts/SearchQueryContext';

export const metadata: Metadata = {
  title: 'Poetry Corner',
  description: 'Generated by hakol.ru',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-neutral_04'>
        <SearchQueryProvider>
          <div className='wrapper'>
            <Header />
            {children}
          </div>
        </SearchQueryProvider>
      </body>
    </html>
  );
}
